<?php

class UsersController extends BaseController
{
    function index()
    {
        parent::index(); // TODO: Change the autogenerated stub
    }

    function register()
    {
        if ($this->isPost) {
            $username = $_POST['username'];
            $email = $_POST['email'];
            $confirm_email = $_POST['confirm_email'];
            $password = $_POST['password'];
            $confirm_password = $_POST['confirm_password'];

            //name can contain only alpha characters, digits, dash and underscore
            if (!preg_match("/^[a-zA-Z0-9_-]{5,}$/", $username)) {
                $username_error = "Username must contain only alphabets and space";

            }
            // checking for valid email
            if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
                $email_error = "Please enter valid email address";

            }

            if ($email != $confirm_email) {
                $confirm_email_error = "Email and Confirm Email doesn't match";

            }
            // password can contain at least 6 characters
            if (strlen($password) < 6) {
                $password_error = "Password must be minimum of 6 characters";

            }
            // check whether password matches with confirm password
            if ($password != $confirm_password) {
                $confirm_password_error = "Password and Confirm Password doesn't match";

            }

            $password_hash = password_hash($password, PASSWORD_BCRYPT);

            $isExistingUser = $this->model->isUserExistsByEmail($email);

            //if user exist set user existing msg and redirect to register
            if ($isExistingUser) {
                $_SESSION['message'] = 'User with this email already exists!';
                header("Location: " . APP_ROOT . "/users/register");
            } else { // if not exists

                if ($this->model->register($username, $password_hash, $email)) {
                    $_SESSION['logged_in'] = true;
                    $_SESSION['username'] = $username;
                    $_SESSION['message'] = 'You are successfully registered!';

                    header('Location: ' . APP_ROOT);
                } else {
                    $_SESSION['message'] = 'Registration failed';
                }

            }
        }
    }

    function login()
    {
        if ($this->isPost) {
            $username = $_POST['username'];
            $password = $_POST['password'];
            $isUserExists = $this->model->isUserExistsByUsername($username);

            // user exists
            if ($isUserExists) {
                $currentUser = $this->model->login($username, $password);
                if (password_verify($_POST['password'], $currentUser['password_hash'])) {
                    $_SESSION['userId'] = $currentUser['id'];
                    $_SESSION['username'] = $currentUser['username'];
                    $_SESSION['logged_in'] = true;
                    $_SESSION['message'] = 'You are logged in!';
                    header('Location: ' .APP_ROOT);
                }

            } else {
                $_SESSION['message'] = "User with that username doesn't exist!";
            }


        }

    }

    function logout()
    {
        session_destroy();
        header('Location: ' .APP_ROOT);
    }
}